import json
import os
from google import genai
from google.genai import types
from dotenv import load_dotenv
from src.csv_processor import stats_processor
from src.insight_engine import generate_insights

load_dotenv()

client = genai.Client(api_key=os.getenv("google_api_key"))


def generate_chart_engine(stats: dict, insights: str):
    stats_json = json.dumps(stats)
    llm_insights = json.loads(insights)

    llm_insights_filtered = llm_insights['insights']
    
    # Code below extracts each catgeory of the insight and it's corressponsing insight
    # and makes a mini dictinonary. This is being done to reduce LLM token usage as it
    # does not need recommendation and scores to identify what charts to make or the
    # fields to choose for it.
    llm_insight_catgeory = [{i['category']: i['insight']} for i in llm_insights_filtered]
    llm_insight_catgeory_json = json.dumps(llm_insight_catgeory)

    system_prompt = f"""You are the expert data and business analyst. You not only show textual insights but also generate support charts and 
    visualizations. You job is to look at the data statistics passed in the dictionary and the insights generated by the LLM. Based on these two
    inputs you decides which columns makes the most sense for which chart type. You will look at the column names, data types, null percentage,
    insights generated and come up with upto 4 charts supporting the insight. 
    1) First is a bar chart which will require a main categorical column for X-asis and a metric/numeric column for Y-Axis. You can also add colour 
    to the chart by a 2nd catgeorical supporting column. Your task is to identify what goes on X-axis, Y-axis and colour.
    2) Second will be another bar chart or a time series chart if a date/timestamp column is present. Based on the insight use your judgement
    which one would be best suited for supporting it. Define clearly columns for X-axis, Y-axis, colour for supporting categories
    3) A base metric/numeric which makes the most sense to show a distribution for. This will be an histogram. Feel free to add 1 categorical
    column for colour or a bifurcation on a histogram if it makes sense according to the data
    4) If it is statistical data and we need to look at correlation, then define metrics for building a scatter plot. This will need
    two numeric/metric columns.

    The decision you have to make is: 
    1) Between 3-5 how many charts are needed and what will be their type. 
    2) For each chart type what will be the columns used.
    3) What columns will go on X-axis, Y-axis, colour. Colour might not apply to 
    every chart. Therefore where it is not applicable or necessary, do not force it. It can be null
    4) Choose an appropriate title for the chart

    Your output should be a json of format:
    {{
        "charts": [
            {{
                "chart_number": 1,
                "x_axis": "column name or null",
                "y_axis": "column name or null",
                "chart_type": "bar/line/histogram/scatter",
                "colour": "column name or null",
                "title": "..."
                
            }}
        ]
    }}
  
    """

    user_message = f"""Dataset statistics: {stats_json}
    Dataset insights by LLM: {llm_insight_catgeory_json}"""

    config = types.GenerateContentConfig(
        temperature=0.7,
        max_output_tokens=8000,
        system_instruction=system_prompt,
        response_mime_type="application/json"
    )

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=user_message,
        config=config
    )

    return response.text

if __name__ == "__main__":
    # stats = stats_processor("data/Superstore.csv")  # commented out to avoid API calls
    # insights = generate_insights("data/Superstore.csv")  # commented out to avoid API calls
    # result = generate_chart_engine(stats, insights)
    # with open('data/cached_charts.json', 'w') as f:
    #     f.write(result)
    
    # Load from cache instead
    with open('data/cached_charts.json', 'r') as f:
        result = f.read()
    print(result)
